applications:
  argocd:
    enabled: true
    name: argocd
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/padilin/k3s-argocdish.git
      targetRevision: main
      path: apps/argocd
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
  radarr:
    enabled: true
    name: radarr
    namespace: argocd
    project: arr
    source:
      repoURL: https://github.com/padilin/k3s-argocdish.git
      targetRevision: main
      path: apps/radarr
    destination:
      server: https://kubernetes.default.svc
      namespace: arr
