---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ $.Release.Namespace }}-data-pvc
    namespace: {{ $.Release.Namespace }}
spec:
    storageClassName: longhorn-nvme
    volumeName: {{ $.Release.Namespace }}-data-pv
    resources:
        requests:
            storage: 5Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteMany
        - ReadOnlyMany
