apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "arr.fullname" $ }}-data-pvc
  namespace: {{ $.Release.Namespace }}
status:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: {{ include "arr.fullname" $ }}-data-pv
  storageClassName: longhorn-nvme
  volumeMode: Filesystem
