apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ include "arr.fullname" $ }}-data-pv
spec:
  capacity:
    storage: 5Gi
  csi:
    driver: driver.longhorn.io
    volumeHandle: {{ include "arr.fullname" $ }}-data-pv
    fsType: xfs
    volumeAttributes:
      diskSelector: nvme
      migratable: 'false'
      nodeSelector: ''
      numberOfReplicas: '2'
      staleReplicaTimeout: '20'
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: {{ $.Release.Namespace }}
    name: {{ include "arr.fullname" $ }}-data-pvc
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-nvme
  volumeMode: Filesystem
