{{- range $appName, $appConfig := .Values.apps }} {{- /* Loop through each app defined in values */}}
{{- if $appConfig.enabled }} {{- /* Only generate if app is enabled */}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arr.fullname" $ }}-{{ $appName }} 
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "arr.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $appName }} # Add specific app label
spec:
  replicas: {{ $appConfig.replicaCount }}
  selector:
    matchLabels:
      {{- include "arr.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $appName }} # Ensure selector includes the specific app
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        {{- include "arr.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $appName }} # Add specific app label to pods
    spec:
      containers:
        - name: {{ $appName }} # Container name based on the app key
          image: "{{ $appConfig.image.repository }}:{{ $appConfig.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $appConfig.image.pullPolicy }}
          {{- if $appConfig.resources }}
          resources:
            {{- toYaml $appConfig.resources | nindent 12 }}
          {{- end }}
          {{- if $appConfig.env }}
          env:
            {{- range $envVar := $appConfig.env }}
            - name: {{ $envVar.name }}
              {{- if $envVar.value }}
              value: {{ $envVar.value | quote }}
              {{- else if $envVar.valueFrom }}
              valueFrom:
                {{- toYaml $envVar.valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}
          {{- end }}
          volumeDevices:
            {{- if $appConfig.configPVC }}
            - name: {{ include "arr.fullname" $ }}-{{ $appName }}-config
              devicePath: /config
            {{- end }}
            {{- if $appConfig.mediaDataPVC }}
            - name: {{ include "arr.fullname" $ }}-media-data
              devicePath: /data
            {{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      volumes:
        {{- if $appConfig.configPVC }}
        - name: {{ include "arr.fullname" $ }}-{{ $appName }}-config
          persistentVolumeClaim:
            claimName: {{ include "arr.fullname" $ }}-{{ $appName }}-config-pvc
        {{- end }}
        {{- if $appConfig.mediaDataPVC }}
        - name: {{ include "arr.fullname" $ }}-media-data
          persistentVolumeClaim:
            claimName: {{ include "arr.fullname" $ }}-media-data-pvc
        {{- end }}
{{- end }}
{{- end }}
