{{- range $appName, $appConfig := .Values.apps }}
{{- range $volName, $volConfig := $appConfig.storage }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "arr.fullname" $ }}{{- if not $volConfig.shared }}-{{ $appName }}{{- end }}-{{ $volName }}-pv
spec:
  capacity:
    storage: {{ $volConfig.size }}
  csi:
    driver: driver.longhorn.io
    volumeHandle: {{ include "arr.fullname" $ }}{{- if not $volConfig.shared }}-{{ $appName }}{{- end }}-{{ $volName }}-pv
    fsType: xfs
    migratable: true
    numberOfReplicas: 2
    staleReplicaTimeout: 480
  accessModes:
    {{- if $volConfig.shared }}
    - ReadWriteMany
    {{- else }}
    - ReadWriteOnce
    {{- end }}
  claimRef:
    kind: PresistentVolumeClaim
    namespace: {{ $.Release.Namespace }}
    name: {{ include "arr.fullname" $ }}{{- if not $volConfig.shared }}-{{ $appName }}{{- end }}-{{ $volName }}-pvc
    apiVersion: v1
  presistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-nvme
  volumeMode: Filesystem
{{- end }}
{{- end }}
