{{- range $appName, $appConfig := .Values.apps }}
{{- range $volName, $volConfig := $appConfig.storage }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "arr.fullname" $ }}{{- if not $volConfig.shared }}-{{ $appName }}{{- end }}-{{ $volName }}-pv
  finalizers:
    - kubernetes.io/pv-protection
    - external-attacher/driver-longhorn-io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  capacity:
    storage: {{ $volConfig.size }}
  csi:
    driver: driver.longhorn.io
    volumeHandle: {{ include "arr.fullname" $ }}{{- if not $volConfig.shared }}-{{ $appName }}{{- end }}-{{ $volName }}-pv
    fsType: xfs
    volumeAttributes:
      diskSelector: nvme
      fsType: xfs
      numberOfReplicas: '2'
      staleReplicaTimeout: '480'
  accessModes:
    {{- if $volConfig.shared }}
    - ReadWriteMany
    {{- else }}
    - ReadWriteOnce
    {{- end }}
  claimRef:
    kind: PersistentVolumeClaim
    namespace: {{ $.Release.Namespace }}
    name: {{ include "arr.fullname" $ }}{{- if not $volConfig.shared }}-{{ $appName }}{{- end }}-{{ $volName }}-pvc
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-nvme
  volumeMode: Filesystem
{{- end }}
{{- end }}
