{{- range $appName, $appConfig := .Values.apps }}
{{- range $volName, $volConfig := $appConfig.storage }}
---
apiVersion: v1
kind: PresistentVolumeClaim
metadata:
  name: {{ include "arr.fullname" $ }}{{- if not $volConfig.shared }}-{{ $appName }}{{- end }}-{{ $volName }}-pvc
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    {{- if $volConfig.shared }}
    - ReadWriteMany
    {{- else }}
    - ReadWriteOnce
    {{- end }}
  resources:
    requests:
      storage: {{ $volConfig.size }}
  volumeName: {{ include "arr.fullname" $ }}{{- if not $volConfig.shared }}-{{ $appName }}{{- end }}-{{ $volName }}-pv
  storageClassName: longhorn-nvme
  volumeMode: Filesystem
{{- end }}
{{- end }}
