apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-test-pvc
  namespace: arr
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: arr-test-volume
  storageClassName: longhorn-nvme
  volumeMode: Filesystem
