apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-test-pv
  finalizers:
    - kubernetes.io/pv-protection
    - external-attacher/driver-longhorn-io
spec:
  capacity:
    storage: 2Gi
  csi:
    driver: driver.longhorn.io
    volumeHandle: arr-test-volume
    fsType: xfs
    volumeAttributes:
      diskSelector: nvme
      fsType: xfs
      numberOfReplicas: '2'
      staleReplicaTimeout: '480'
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: arr
    name: arr-test-pvc
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-nvme
  volumeMode: Filesystem
