apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-nvme
spec: {}
provisioner: driver.longhorn.io
parameters:
  diskSelector: nvme
  fsType: xfs
  numberOfReplicas: '2'
  staleReplicaTimeout: '480'
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
