{{- range $appName, $appConfig := .Values.apps }}
{{- range $volName, $volConfig := $appConfig.storage }}
---
apiVersion: longhorn.io/v1beta2
kind: VolumeAttachment
metadata:
  finalizers:
    - longhorn.io
  name: {{ include "arr.fullname" $ }}{{- if not $volConfig.shared }}-{{ $appName }}{{- end }}-{{ $volName }}-va
  namespace: storage
  annotations:
    argocd.argoproj.io/sync-wave: "4" # after volumeAttachment
spec:
  volume: {{ include "arr.fullname" $ }}{{- if not $volConfig.shared }}-{{ $appName }}{{- end }}-{{ $volName }}-vol
{{- end }}
{{- end }}
