name: jackett
apps:
  - name: webtop
    enabled: true
    kind: deployment
    replicaCount: 1
    root: true
    image:
      repository: lscr.io/linuxserver/webtop
      tag: latest
      pullPolicy: IfNotPresent
    ports:
      - name: webtop-http
        protocol: TCP
        port: 3000
    env:
      - name: TZ
        value: America/Chicago
      - name: PUID
        value: 1000
      - name: PGID
        value: 1000
  - name: jackett
    enabled: true
    kind: deployment
    replicaCount: 1
    image:
      repository: lscr.io/linuxserver/jackett
      tag: latest
      pullPolicy: IfNotPresent
    gluetun:
      env:
        - name: TZ
          value: America/Chicago
        - name: UPDATE_PERIOD
          value: 24h
        - name: VPN_TYPE
          value: wireguard
        - name: PORT_FORWARD_ONLY
          value: on
        - name: VPN_PORT_FORWARDING_UP_COMMAND
          value: /bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'
        - name: VPN_SERVICE_PROVIDER
          valueFrom:
            secretKeyRef:
              name: arr-gluetun-secret
              key: vpn_service_provider
        - name: WIREGUARD_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: arr-gluetun-secret
              key: wireguard_private_key
        - name: SERVER_COUNTRIES
          valueFrom:
            secretKeyRef:
              name: arr-gluetun-secret
              key: server_countries
    env:
        - name: TZ
          value: America/Chicago
        - name: AUTO_UPDATE
          value: true
    storage:
      - name: config
        shared: false
        path: /config
        size: 5Gi
        pvc: true
      - name: mediadata
        shared: true
        path: /data
        subPath: ./torrents/blackhole
        size: 5Gi
        pvc: true
    ports:
      - name: jackett-http
        protocol: TCP
        port: 9117
