name: jellyfin
apps:
  - name: jellyfin
    enabled: true
    kind: deployment
    replicaCount: 1
    root: true
    image:
      repository: lscr.io/linuxserver/jellyfin
      tag: latest
      pullPolicy: IfNotPresent
    env:
        - name: TZ
          value: America/Chicago
    storage:
      - name: config
        shared: false
        path: /config
        size: 5Gi
        pvc: true
      - name: mediadata
        shared: true
        path: /data
        subPath: ./media
        size: 5Gi
        pvc: true
      - name: decoder
        shared: false
        path: /dev/video19
        hostPath: /dev/video19
        pvc: false
    ports:
      - name: jellyfin-http
        protocol: TCP
        port: 8096
