apps:
  radarr:
    enabled: true
    replicaCount: 1
    image:
      repository: lscr.io/linuxserver/radarr
      tag: 5.21.1.9799-ls270
      pullPolicy: IfNotPresent
  sonarr:
    enabled: true
    replicaCount: 1
    image:
      repository: lscr.io/linuxserver/sonarr
      tag: 4.0.14.2939-ls279
      pullPolicy: IfNotPresent
    resources:
      limits:
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 50mi
