apps:
  radarr:
    enabled: true
    replicaCount: 1
    image:
      repository: lscr.io/linuxserver/radarr
      tag: 5.21.1.9799-ls270
      pullPolicy: IfNotPresent
    env:
      - name: TZ
        value: America/Chicago
    storage:
      config:
        shared: false
        path: /config
        size: 5Gi
        pvc: true
      media-data:
        shared: true
        path: /data
        size: 5Gi
        pvc: true
  sonarr:
    enabled: true
    replicaCount: 1
    image:
      repository: lscr.io/linuxserver/sonarr
      tag: 4.0.14.2939-ls279
      pullPolicy: IfNotPresent
    env:
      - name: TZ
        value: America/Chicago
    storage:
      config:
        shared: false
        path: /config
        size: 5Gi
        pvc: true
      media-data:
        shared: true
        path: /data
        size: 5Gi
        pvc: true
  qbittorrent:
    enabled: true
    replicaCount: 1
    image:
      repository: lscr.io/linuxserver/qbittorrent
      tag: latest
      pullPolicy: IfNotPresent
    env:
      - name: TZ
        value: America/Chicago
    storage:
      config:
        shared: false
        path: /config
        size: 5Gi
        pvc: true
      media-data:
        shared: true
        path: /data
        size: 5Gi
        subPath: torrents
        pvc: true
  overseerr:
    enabled: true
    replicaCount: 1
    image: 
      repository: lscr.io/linuxserver/overseerr
      tag: latest
      pullPolicy: IfNotPresent
    env:
      - name: TZ
        value: America/Chicago
    storage:
      config:
        shared: false
        path: /config
        size: 5Gi
        pvc: true
  jellyfin:
    enabled: true
    replicaCount: 1
    image: 
      repository: lscr.io/linuxserver/jellyfin
      tag: 10.10.7
      pullPolicy: IfNotPresent
    env:
      - name: TZ
        value: America/Chicago
    storage:
      config:
        shared: false
        path: /config
        size: 5Gi
        pvc: true
      hwaccel:
        hostPath: /dev/video19
        path: /dev/video19
        pvc: false
      media-data:
        shared: true
        path: /media
        size: 5Gi
        subPath: media
        pvc: true
