{{- define "library-templates._pvc.tpl" -}}
{{- range $appName, $appConfig := .Values.apps }}
{{- range $volName, $volConfig := $appConfig.storage }}
{{- if eq $volConfig.pvc true }}
{{- if eq $volConfig.shared false }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-{{ $appName }}-{{ $volName }}-pvc
  namespace: {{ $.Release.Namespace }}
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: {{ $volConfig.size }}
  storageClassName: longhorn-arr
  volumeMode: Filesystem
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
