name: tdarr
apps:
  - name: tdarr-server
    enabled: true
    kind: deployment
    replicaCount: 1
    image:
      repository: ghcr.io/haveagitgat/tdarr
      tag: latest
      pullPolicy: Always
    env:
        - name: TZ
          value: America/Chicago
        - name: PUID
          value: 1000
        - name: PGID
          value: 1000
        - name: serverIP
          value: 0.0.0.0
        - name: serverPort
          value: 8266
        - name: webUIPort
          value: 8265
        - name: internalNode
          value: true
        - name: inContainer
          value: true
        - name: nodeName
          value: mainNode
    storage:
      - name: serverconfig
        path: /app/server
        shared: false
        size: 5Gi
        pvc: true
      - name: tdarrconfigs
        shared: true
        path: /app/configs
        pvc: true
      - name: tdarrlogs
        shared: true
        path: /app/logs
        pvc: true
      - name: mediadata
        shared: true
        path: /media
        subPath: ./media
        pvc: true
      - name: transcodecache
        shared: true
        path: /temp
        pvc: true
    ports:
      - name: tdarr-webui-http
        protocol: TCP
        port: 8265
      - name: tdarr-server-http
        protocol: TCP
        port: 8266
  - name: tdarr-node
    enabled: true
    kind: deployment
    replicaCount: 1
    image:
      repository: ghcr.io/haveagitgat/tdarr_node
      tag: latest
      pullPolicy: Always
    env:
        - name: TZ
          value: America/Chicago
        - name: PUID
          value: 1000
        - name: PGID
          value: 1000
        - name: serverIP
          value: 0.0.0.0
        - name: serverPort
          value: 8266
        - name: inContainer
          value: true
        - name: nodeName
          value: extraNode
    storage:
      - name: tdarrconfigs
        shared: true
        path: /app/configs
        pvc: true
      - name: tdarrlogs
        shared: true
        path: /app/logs
        pvc: true
      - name: mediadata
        shared: true
        path: /media
        subPath: ./media
        pvc: true
      - name: transcodecache
        shared: true
        path: /temp
        pvc: true
