name: tautulli
apps:
  - name: tautulli
    enabled: true
    kind: deployment
    replicaCount: 1
    image:
      repository: lscr.io/linuxserver/tautulli
      tag: latest
      pullPolicy: Always
    env:
        - name: TZ
          value: America/Chicago
        - name: PUID
          value: 1000
        - name: PGID
          value: 1000
    storage:
      - name: config
        shared: false
        path: /config
        size: 5Gi
        pvc: true
    ports:
      - name: tautulli-http
        protocol: TCP
        port: 8181
