name: jellyseerr
apps:
  - name: jellyseerr
    enabled: true
    kind: deployment
    replicaCount: 1
    image:
      repository: fallenbagel/jellyseerr
      tag: latest
      pullPolicy: IfNotPresent
    env:
        - name: TZ
          value: America/Chicago
        - name: AUTO_UPDATE
          value: true
    storage:
      - name: config
        shared: false
        path: /config
        size: 5Gi
        pvc: true
    ports:
      - name: jellyseerr-http
        protocol: TCP
        port: 5055
