{{- range $appName, $appConfig := .Values.apps }} {{- /* Loop through each app defined in values */}}
{{- if $appConfig.enabled }} {{- /* Only generate if app is enabled */}}
{{- if eq $appConfig.kind "stateful" }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Values.name }}-{{ $appConfig.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    helm.sh/chart: {{ $.Values.name }}-{{ $.Chart.Version }}
    app.kubernetes.io/name: {{ $.Values.name }}-{{ $appConfig.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- if $.Chart.AppVersion }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/component: {{ $appConfig.name }}
spec:
  serviceName: {{ $appConfig.name }}-svc
  replicas: {{ $appConfig.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $.Values.name }}-{{ $appConfig.name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ $appConfig.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $.Values.name }}-{{ $appConfig.name }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/component: {{ $appConfig.name }}
    spec:
      containers:
        {{- if $appConfig.gluetun }}
        - name: {{ $appConfig.name }}-gluetun
          image: qmcgaw/gluetun
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
            runAsUser: 0
          volumeMounts:
            - name: arr-{{ $appConfig.name }}-gluetun
              mountPath: /gluetun
          env:
            {{- range $envVar := $appConfig.gluetun.env }}
            - name: {{ $envVar.name }}
              {{- if $envVar.value }}
              value: {{ $envVar.value | quote }}
              {{- else if $envVar.valueFrom }}
              valueFrom:
                {{- toYaml $envVar.valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}
        {{- end }}
        - name: {{ $appConfig.name }} # Container name based on the app key
          image: "{{ $appConfig.image.repository }}:{{ $appConfig.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $appConfig.image.pullPolicy }}
          {{- if $appConfig.resources }}
          resources:
            {{- toYaml $appConfig.resources | nindent 12 }}
          {{- end }}
          {{- if $appConfig.env }}
          env:
            {{- range $envVar := $appConfig.env }}
            - name: {{ $envVar.name }}
              {{- if $envVar.value }}
              value: {{ $envVar.value | quote }}
              {{- else if $envVar.valueFrom }}
              valueFrom:
                {{- toYaml $envVar.valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}
          {{- end }}
          volumeMounts:
            {{- range $volumeConfig := $appConfig.storage }}
              {{- if $volumeConfig.shared }}
            - name: arr-shared-{{ $volumeConfig.name }}-pvc
              {{- else }}
            - name: arr-{{ $appConfig.name }}-{{ $volumeConfig.name }}-pvc
              {{- end }}
              mountPath: {{ $volumeConfig.path }}
              {{- if $volumeConfig.subPath }}
              subPath: {{ $volumeConfig.subPath }}
              {{- end }}
            {{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      {{- if $appConfig.storageAffinity }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: storage-type
                  operator: In
                  values:
                    - nvme
      {{- end }}
      volumes:
        {{- range $volumeConfig := $appConfig.storage }}
        {{- if $volumeConfig.pvc }}
          {{- if $volumeConfig.shared }}
        - name: arr-shared-{{ $volumeConfig.name }}-pvc
          {{- else }}
        - name: arr-{{ $appConfig.name }}-{{ $volumeConfig.name }}-pvc
          {{- end }}
          persistentVolumeClaim:
            {{- if $volumeConfig.shared }}
            claimName: arr-shared-{{ $volumeConfig.name }}-pvc
            {{- else }}
            claimName: arr-{{ $appConfig.name }}-{{ $volumeConfig.name }}-pvc
            {{- end }}
        {{- else }}
        - name: {{ $.Values.name }}{{- if not $volumeConfig.shared}}-{{ $appConfig.name }}{{- end }}-{{ $volumeConfig.name }}
          hostPath:
            path: {{ $volumeConfig.hostPath }}
        {{- end }}
        {{- end }}
  # volumeClaimTemplates:
  #   {{- range $volName, $volConfig := $appConfig.storage }}
  #   {{- if $volConfig.pvc }}
  #   - metadata:
  #       name: arr{{- if not $volConfig.shared }}-{{ $appName }}{{- end }}-{{ $volName }}-pvc
  #     spec:
  #       accessModes:
  #         {{- if $volConfig.shared }}
  #         - ReadWriteMany
  #         {{- else }}
  #         - ReadWriteOncePod
  #         {{- end }}
  #       storageClassName: longhorn-arr
  #       resources:
  #         requests:
  #           storage: {{ $volConfig.size }}
  #   {{- end }}
  #   {{- end }}
{{- end }}
{{- end }}
{{- end }}
