{{- range $appName, $appConfig := .Values.applications }}
{{- if $appConfig.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appConfig.name }}
  namespace: {{ $appConfig.namespace | default "default" }} 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/managed-by: helm-app-of-apps
spec:
  project: {{ $appConfig.project | default "default" }}
  
  ignoreDifferences:
  - group: "" # For core Kubernetes resources like PersistentVolumeClaim
    kind: PersistentVolumeClaim
    name: arr-media-data-pvc # The specific PVC to ignore differences on
    namespace: arr # The namespace of the PVC
    jsonPointers:
      - /metadata/labels # Ignore all label differences on this PVC
  
  source:
    repoURL: {{ $appConfig.source.repoURL | quote }}
    
    {{- if $appConfig.source.path }}
    path: {{ $appConfig.source.path | quote }}
    {{- end }}
    
    {{- if $appConfig.source.chart }}
    chart: {{ $appConfig.source.chart | quote }}
    {{- end }}

    targetRevision: {{ $appConfig.source.targetRevision | quote }}

    helm:
    {{- if $appConfig.source.helm }}
      {{- if $appConfig.source.helm.valueFiles }}
      valueFiles:
      {{- range $valueFile := $appConfig.source.helm.valueFiles }}
        - {{ $valueFile | quote }}
      {{- end }}
      {{- end }}
      
      {{- if $appConfig.source.helm.values }}
      values: |
{{ $appConfig.source.helm.values | indent 8 }}
      {{- end }}

      {{- if $appConfig.source.helm.parameters }}
      parameters:
      {{- range $param := $appConfig.source.helm.parameters }}
        - name: {{ $param.name | quote }}
          value: {{ $param.value | quote }}
      {{- end }}
      {{- end }}
    {{- else }}
      values: |
        apps:
{{ $appName | toYaml | indent 10 }}:
{{ $appConfig | toYaml | indent 12 }}
        gluetun:
{{ $.Values.gluetun | toYaml | indent 10 }}
        {{- if $appConfig.sharedStorageRoot }}
        allSharedPVC:
          {{- range $otherName, $otherApps := $.Values.applications }}
          {{- if $otherApps.storage }}
          {{- range $otherStoreName, $otherStoreConfig := $otherApps.storage }}
          {{- if $otherStoreConfig.shared }}
          {{ $otherStoreName }}:
            pvc: true
            shared: true
            size: {{ $otherStoreConfig.size }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
        {{- end }}
    {{- end }}

  destination:
    server: {{ $appConfig.destination.server | quote }}
    namespace: {{ $appConfig.destination.namespace | quote }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

{{- end }}
{{- end }}
